-- 0000_core_tables (chapter 2.1): GENERATED by drizzle-kit from
-- src/db/schema.ts, then reviewed against SAD §6.1 — the ADR-16 drift
-- check. Review disposition: column-for-column identical to §6.1 for the
-- four tenant-bearing tables (CHECKs, DR-01/02 UNIQUEs, DR-03 partial
-- unique index, §6.3 hot-path indexes all present); differences are
-- formal only (alphabetical table order with FKs as ALTER TABLE, quoted
-- identifiers, explicit ON DELETE NO ACTION and DESC NULLS LAST — all
-- Postgres defaults spelled out). `applications` (stub) and `members`
-- remain this chapter's recorded decisions; see the DECISION comments in
-- schema.ts. Applied by src/db/migrate.ts — versioned, forward-only.

CREATE TABLE "applications" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "channels" (
	"id" uuid PRIMARY KEY NOT NULL,
	"environment_id" uuid NOT NULL,
	"external_id" text NOT NULL,
	"type" text NOT NULL,
	"name" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"last_sequence" bigint DEFAULT 0 NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "channels_environment_id_external_id_unique" UNIQUE("environment_id","external_id"),
	CONSTRAINT "channels_type_check" CHECK ("channels"."type" IN ('public','private'))
);
--> statement-breakpoint
CREATE TABLE "environments" (
	"id" uuid PRIMARY KEY NOT NULL,
	"application_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"signing_secret" text NOT NULL,
	"retention_days" integer,
	"quota_config" jsonb DEFAULT '{}'::jsonb NOT NULL,
	CONSTRAINT "environments_kind_check" CHECK ("environments"."kind" IN ('development','production'))
);
--> statement-breakpoint
CREATE TABLE "members" (
	"channel_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "members_channel_id_user_id_pk" PRIMARY KEY("channel_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" uuid PRIMARY KEY NOT NULL,
	"channel_id" uuid NOT NULL,
	"sequence" bigint NOT NULL,
	"user_id" uuid,
	"text" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"attachments" jsonb,
	"idempotency_key" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"edited_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "messages_channel_id_sequence_unique" UNIQUE("channel_id","sequence")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY NOT NULL,
	"environment_id" uuid NOT NULL,
	"external_id" text NOT NULL,
	"display_name" text,
	"avatar_url" text,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"banned_at" timestamp with time zone,
	CONSTRAINT "users_environment_id_external_id_unique" UNIQUE("environment_id","external_id")
);
--> statement-breakpoint
ALTER TABLE "channels" ADD CONSTRAINT "channels_environment_id_environments_id_fk" FOREIGN KEY ("environment_id") REFERENCES "public"."environments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "environments" ADD CONSTRAINT "environments_application_id_applications_id_fk" FOREIGN KEY ("application_id") REFERENCES "public"."applications"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "members" ADD CONSTRAINT "members_channel_id_channels_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "members" ADD CONSTRAINT "members_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_channel_id_channels_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_environment_id_environments_id_fk" FOREIGN KEY ("environment_id") REFERENCES "public"."environments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "members_user_channel" ON "members" USING btree ("user_id","channel_id");--> statement-breakpoint
CREATE UNIQUE INDEX "messages_idem" ON "messages" USING btree ("channel_id","idempotency_key") WHERE "messages"."idempotency_key" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "messages_channel_seq" ON "messages" USING btree ("channel_id","sequence" DESC NULLS LAST);