-- 0001 (chapter 2.4): GENERATED by drizzle-kit, then reviewed.
--
-- 0000 created messages_channel_seq on (channel_id, sequence DESC) for
-- history pagination, per SAD §6.3 as it stood. Measured at 50,000 rows,
-- the planner never used it: it walks DR-01's UNIQUE (channel_id, sequence)
-- BACKWARD instead, and dropping this index changed neither the plan nor
-- the cost estimate (0.41..5.04 either way). A btree is bidirectional, so a
-- DESC twin of an existing ASC index adds no ordering — only write
-- amplification on the send path and storage.
--
-- Review disposition: one statement, exactly the intended drop, nothing
-- else. Forward-only as always — 0000 stays true at its own tag, and this
-- file is how the correction travels (SAD §6.3 amended 2026-08-02, v1.1).

DROP INDEX "messages_channel_seq";